version: "3.8"
secrets:
  aws_access_key_id: 
    file: aws_access_key.txt
  aws_secret_access_key: 
    file: aws_secret.txt
  tf_api_token:
    file: tf_api_token.txt
volumes:
  shared-workspace:
    driver: local
services:
  dynamodb-local:
    command: "-jar /Users/stevenhurwitt/dynamodb-local/DynamoDBLocal.jar -sharedDb -dbPath ./dynamodb"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
 